export const locations = [
 {'name': 'Central Methodist Chruch',
     'coords': [-1.0787473438622577, 53.959479435189145],
     'image': 'https://www.yorkpress.co.uk/resources/images/13872524/?type=responsive-gallery-fullscreen',
     'description': '',
     'occupation': '1840',
     'tldr': 'The Central Methodist Church was constructed in 1840, as the Centenary Chapel, marking the 100th anniversary of the founding of the first Methodist societies. In 1887, the chapel became the head of a circuit. The chapel can seat 1,500 worshipers in a horseshoe formation, some on oval gallery above.',
     'events': []},
    {'name': 'York Unitarian Chapel',
     'coords': [-1.0775474761089097, 53.96032658385882],
     'image': 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Unitarian_Chapel_York.jpg',
     'description': '',
     'occupation': '1692',
     'tldr': 'With the passing of The Toleration Act in 1689, most non-conformists across England were granted freedom of worship. Three years later, this church was the first non-conformist church to be built in York, also being the first brick church of any size in the city. It is built in the form of a Greek cross. The major benefactor was Lady Sarah Hewley, with the land most likely belonging to her.',
     'events': []},
    {'name': 'Ketmongergate',
     'coords': [-1.0791760960663104, 53.959267785882346],
     'image': 'https://upload.wikimedia.org/wikipedia/commons/d/d4/St_Saviourgate_-_geograph.org.uk_-_667193.jpg',
     'description': '',
     'occupation': '1175-1368 ',
     'tldr': 'During the construction of many of these houses, large quantities of animal horns and bones were dug up. This is because St Saviourgate’s old name was Ketmongergate, which directly translates to ‘road of the flesh-sellers’. This name was first mentioned in 1175, before the street adopted its current name from the church in 1368.',
     'events': []},
    {'name': "Lady Hewley’s Almshouses",
     'coords': [-1.0777954272235657, 53.95979721243331],
     'image': 'https://upload.wikimedia.org/wikipedia/commons/4/40/City_of_York_-_2-10_%28consecutive%29_and_8A%2C_Lady_Hewley%27s_Almshouses_-_20230729132829.jpg',
     'description': '',
     'occupation': '1700 ',
     'tldr': 'In 1700, Lady Hewley founded almshouses on Tanner Row for ten poor, protestant, over-55 year old women. They moved to this location in 1839 when the Railway Station (old railway at The Grand) needed the land. 325 years later, the almshouses are still operating via the same trust. The wall facing the road contains two inscriptions: the first floor window is filled by an original tablet recording the foundation in Tanner Row in 1700; below is an inscribed stone recording the refounding of the Hospital in 1840.',
     'events': []},
    {'name': 'Rear Admiral Hugh Robinson',
     'coords': [-1.077657585066365, 53.960075933958734],
     'image': 'https://morethannelson.com/wp-content/uploads/2016/02/387px-John_Robinson_Bond-242x300.jpg',
     'description': '',
     'occupation': '1735-1802 ',
     'tldr': 'Rear Admiral Hugh Robinson was the brother of John Robinson, Secretary to the Treasury in Lord North’s government. Admiral Robinson returned to England following the loss of his ship, the Guadoloupe, to the French at the Battle of Cape Henry (1781). With his brother no longer in Government he could not secure another commission, despite George III’s reputed fondness for him (George declared that ‘Captain Robinson was well-bred’). He retired gracefully and moved to this house with his family. Hugh died suddenly in this house in 1802 but his wife and 13 children lived here until 1835.',
     'events': []},
    {'name': "Haughton’s School",
     'coords': [-1.0775274979294998, 53.960163122485106],
     'image': 'https://www.yorkpress.co.uk/resources/images/2679511/?type=responsive-gallery-fullscreen',
     'description': '',
     'occupation': '1773-1935 ',
     'tldr': "In 1773, William Haughton, a former Sheriff of York, left £1300 towards the education of 20 poor children in this area. In 1824 there were said to be '20 or 30 poor boys taught by the rector, English, writing and arithmetic free, and such whose parents desire it and are properly qualified, Latin'. In 1864 there were said to be 34 boys attending in a small room rented by the master. The school moved locations a few times but settled here in 1901.",
     'events': []},
    {'name': 'Lady Sarah Hewley',
     'coords': [-1.0773084681790648, 53.960222965856616],
     'image': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Portrait_of_Sarah_Woolryce_(1627-1710).jpg/500px-Portrait_of_Sarah_Woolryce_(1627-1710).jpg',
     'description': 'Sarah Hewley lived here, funded the building of the Church here, now her almshouses charity lives here.',
     'occupation': '1627-1710 ',
     'tldr': 'Lady Hewley is known for providing charity that would far outlive her existence. She inherited great fortune from her parents and married John Hewley. John was a prominent lawyer and MP for Pontefract and York. He died in 1697 with Lady Hewley inheriting large sums of money. She quickly dedicated all of her fortune to her almshouses, and lived here next to the church. She died here in 1710, instructing that her body should be disposed of cheaply and without ceremony.',
     'events': []},
    {'name': "St Saviour’s Church",
     'coords': [-1.0781376450931568, 53.95954431575061],
     'image': 'https://www.digyork.co.uk/wp-content/uploads/2023/05/St.-Saviour-Church.webp',
     'description': '',
     'occupation': 'C11th ',
     'tldr': 'Although the current building dates to the 15th century, this church was founded in the 11th century. It was originally known as ‘St Saviour in the Marsh’ due to the marshy lands in this area of York. It is now used by the York Archaeological Trust, where one of York’s greatest historic artifacts is kept. A roman skeleton, found in a Roman cemetery in York, contains a lion bite - this is the first direct physical evidence of gladiatorial combat between men and wild beasts anywhere on the planet.',
     'events': []},
    {'name': 'Eboracum Lodge 1611',
     'coords': [-1.0779324783621662, 53.95992763699054],
     'image': 'https://larcombe.fr/wp-content/uploads/building.jpg',
     'description': '',
     'occupation': '1845 ',
     'tldr': 'This building was constructed as the Mechanics Institute,, to improve the education of working men. It was bought by Eboracum Lodge 1611 (Freemasons) in 1883, who were consecrated in 1876 in Micklegate. In 1878 the lodge first entertained American brethren who later presented a silver collarette which since then has been annually presented to the newly installed Master to be worn at all meetings held within the lodge and this established a tradition of welcoming international visitors.',
     'events': []},
  ];
